### ISSUE TITLE
Implement CookieManager

### ISSUE THREAD

**Issue by pmk724** [pmk724/OUTWAR#1]
Need to research which packages C# offers to implement something to manage cookies/sessions.

Looks like C# has this built in in the form of CookieContainer. I pulled the MSDN documentation on this [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.cookiecontainer.getcookies?view=netframework-4.7.2).

**Comment by deadringer21** [comment]
This seems to be handled pretty well by the HttpClient object in the standard "net" package of C#.  No further work is needed on this until later on when we get to complicated multi-threaded processes such as casting skills.
